### ISSUE TITLE
Null Return on Group scrubs a github team

### ISSUE THREAD

**Issue by jerick1976** [github/ldap-teamsync#6]
We experienced an issue within our AD environment where the sync script hit a heavily loaded AD server.  The result was a query return of zero users for a group that had multiple users in it.  The script then proceeded to remove all of the users from the GitHub team.  

On the next run the script hit a lightly loaded AD server and repopulated the team but the damage was done.

The request here is to add a check for a null list.  If the list is empty, report an error and proceed to the next sync instead of stripping the users from the GitHub team.

**Comment by primetheus** [comment]
@jerick1976 this sounds like you're using the `-s|--sync` option. What you're looking for _should_ be handled by using the `-a|--add` flag instead of doing a sync... this way, only new users in the AD group will be added to the team in GitHub. If that's not what you want, is there a particular reason why an AD group would return `NULL` and this would not be considered a valid return?

**Comment by primetheus** [comment]
We can probably add an option to skip null responses... maybe `-n|--skip-null` or something of the like... that way existing functionality can remain for those who want it, and when we want empty groups to be ignored we can do that

**Comment by primetheus** [comment]
@jerick1976 I've refactored the script to run as a GitHub App in #33. I need to add more checks in, but the `CHANGE_THRESHOLD` should help with this issue

**Comment by primetheus** [comment]
Closing. If further functionality is requested please re-open
